spring:
  application:
    name: service-acupoint
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.45.249/acupoint
    username: wang
    password: 123456
  ai:
    dashscope:
      api-key: ${API-KEY}
      chat:
        options:
          model: qvq-max-latest
          multi-model: true
    openai:
      chat:
        options:
          model: qwen-vl-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${API-KEY}
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      lettuce:
        pool:
          max-active: 16 #最大连接数
          max-wait: 5000ms #阻塞时间
          max-idle: 8 #最大空闲连接数
          min-idle: 1 #最小空闲连接数
logging:
  level:
    org.springframework.ai: debug
server:
  port: 8081
API-KEY: sk-c945ce6294914aefa52b0e3ea4ea2afe
