spring:
  application:
    name: service-acupoint
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.45.249:3306/acupoint?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: wang
    password: 123456
